version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.2.0
    - 9.0.0
    - 9.1.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.20.0
    - 2.20.2
    - 2.20.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.5
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.5
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: mockdate
    versions:
    - 3.0.3
    - 3.0.5
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
    - 17.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: "@storybook/addon-storyshots"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
